apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-om1c
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-sqqt-tenant/rhtap-demo-app/hacbs-test-project-om1c@sha256:b6f24c6905653c0c3db8eb718017ba9bca6298866f418d47354cad7118615fae
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
